# Generated by Django 4.1.1 on 2022-09-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_period_delete_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='technologies',
        ),
        migrations.AddField(
            model_name='projects',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.programminglang'),
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.technology'),
        ),
    ]
