# Generated by Django 4.1.1 on 2022-09-20 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_period_remove_projects_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='period',
        ),
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
