# Generated by Django 4.1.1 on 2022-09-18 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_on',
            field=models.DateField(default=datetime.date(2022, 9, 18)),
        ),
    ]
