# Generated by Django 4.1.1 on 2022-09-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_update_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_on',
        ),
    ]
