# Generated by Django 4.1.1 on 2022-09-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_update_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
