# Generated by Django 4.1.1 on 2022-09-19 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_tag_remove_post_image_remove_post_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 18, 3, 48, 286396)),
        ),
    ]
