# Generated by Django 4.1.1 on 2022-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
